### ISSUE TITLE
Exception : corrupted hmac detected

### ISSUE THREAD

**Issue by fwininger** [net-ssh/net-ssh#728]
### Actual behavior

In some case, I have this error :
- corrupted hmac detected

### System configuration

- net-ssh master
- Ruby 2.6.1

### related issue 

Other people seems to have also this kind of problem :
https://github.com/ytti/oxidized/issues/1952

**Comment by fwininger** [comment]
Did you have any idea to solve this kind of issue ?

**Comment by mfazekas** [comment]
@fwininger first step would be some kind of somewhat reliable way to reproduce. 
Then I'd try to add some logging to figure out what can be the issue.

But it doesn't sound trivial at all.

**Comment by stillhart** [comment]
I experienced this issue too using net-ssh and I can reproduce it on our equipment. In my case I am using https://github.com/swisscom/net-ssh-cli. It only happens when I run certain commands on my machines. @fwininger What devices are you connecting to using oxidized?

I will try to reproduce this using only net-ssh.

**Comment by fwininger** [comment]
I have no idea to reproduce this error systematically, but I use directly Net::SSH over 10000 VMs.

**Comment by stillhart** [comment]
I could reproduce the error using plain net-ssh on our equipment. It happens after a random amount of tries but it does happen after a while.
https://gist.github.com/stillhart/70785e3e1ee8dc3f43e0200c0e22f5de

The error happens here when receiving a few hundret our thousand lines of text:
```ruby
channel.send_data "display event history all list\n"
until output[/#\z/] do
   ssh.process(0.000001) 
end
```

Does anybody have an idea how to debug this further? How can I find out if the device is the issue or net-ssh?

**Comment by mfazekas** [comment]
@stillhart one thing i'd try is logging a lot of stuff at the place we throw the exception:

https://github.com/net-ssh/net-ssh/blob/5c31c9dc5f65b151a9195d1d7c307e2f6d155da1/lib/net/ssh/transport/packet_stream.rb#L251-L266

So i'd do something like this at line l263:
```ruby
if real_hmac != my_computed_hmac 
  puts "Real hmac: #{real_hmac.inspect}"
  puts "My hmac: #{my_computed_hmac}"
  puts "packet_length: #{@packet_length} padding_length: #{padding_length}"
  puts "server.hmac.mac_length: #{server.hmac.mac_length}"
  puts "server.hmac.etm :#{server.hmac.etm}"
  raise Net::SSH::Exception, "corrupted hmac detected"
end
```

then that might give us more information on what's going on.

**Comment by fwininger** [comment]
@stillhart do you have the version of the openssh-server ?

**Comment by fwininger** [comment]
For me, I have this error on openssh-server version 7.4, official package from Centos / Redhat / Debian.

I realy don't understand the issue, your monitoring start to report this issue on 15 november and the frequency increase from this date.

We never had this error with commit 30936b9f393604cb9c3c08d265a2d3186851647e but it's start with 7bf0db25931ac604d742dc0c472bec20f7eb6516.

**Comment by fwininger** [comment]
A list of openssh-server that occur this error :
- debian 9 : openssh-server : 1:7.4p1-10+deb9u6
- oracle linux server 7.6 : openssh-server : 7.4p1-16.el7
- amazon linux 2 : openssh-server : 7.4p1-16.amzn2.0.6
- amazon linux 2 : openssh-server :  7.4p1-21.amzn2.0.1
- centos 7 : openssh-server : 7.4p1-16.el7

**Comment by amvasilyev** [comment]
Hello. I came across this issue when initiating connection with Centos 7 on AWS.

**Comment by wangthony** [comment]
Also on Debian 10.2:
OpenSSH_7.9p1 Debian-10+deb10u1, OpenSSL 1.1.1d  10 Sep 2019

**Comment by stillhart** [comment]
I just got one in the net-ssh Travis/CI Pipeline for my (very) old merge request:

https://travis-ci.org/net-ssh/net-ssh/jobs/652904318#L1003

**Comment by fzipi** [comment]
Same here, FreeBSD 11.3:
OpenSSH_7.5p1, OpenSSL 1.0.2s-freebsd  28 May 2019

**Comment by fzipi** [comment]
Added puts from https://github.com/net-ssh/net-ssh/issues/728#issuecomment-557127840, and here is the output:
```
Real hmac: "N^\x9CN]\t\x10\f\r\xB7\x9F\x1C\xEC:)\xC4\xC2^j GD\xF1;WRq\xB42I\xCD\xC9"
My hmac: G�h�w�3��{��pS�3v��{׉99�C��
packet_length: 64 padding_length: 13
server.hmac.mac_length: 32
server.hmac.etm :true
Real hmac: "F:d\x12\x98km.wF\xBD)\x1DW\xACQ\xBD\x0Fip7\\\xFF\xCB\xBD\x14\xAE\\b\xE0\xB8\x06"
My hmac: oIC�	ى�ZFm���Y`�e�m�6hD�Cp�
packet_length: 64 padding_length: 226
server.hmac.mac_length: 32
server.hmac.etm :true
Real hmac: "\x90\x1C\x1DC\xF6`\x9Dz\xB3\x93@\x9E\xE4K\x94\x19G\xC8T8\xF2\x8B[\xF4\x1F\x97Zx\xE8,|T"
c�WUfJ]���^�=MS?��Xy�
packet_length: 64 padding_length: 97
server.hmac.mac_length: 32
server.hmac.etm :true

```

**Comment by fzipi** [comment]
Also, using ruby 2.6.5 and test-kitchen 2.3.4.

**Comment by mfazekas** [comment]
@fzipi many thanks for the debug log, i've updated the instructions to output Real/my hmac in the same format, but should not make much difference. I don't see any obvious issue there. 

It's good to know that it's `etm` related. It was a recent addition.
See - #714 

@graaff any insight, or tips what we need to gather to debug this?!

**Comment by fzipi** [comment]
@mfazekas Sure, let me know if you need anything else. I still have that branch available. I can test with the rc1 if you want, but I don't think there was any change regarding this specifically.

**Comment by mfazekas** [comment]
@fzipi one thing you can try - if you can repro the issue 100% then try with those options in Net:SSH:

- `hmac: ['hmac-sha2-256-etm@openssh.com']`
- `hmac: ['hmac-sha2-512-etm@openssh.com']`
- `hmac: ['hmac-sha2-256']`
- `hmac: ['hmac-sha2-512']`

**Comment by mfazekas** [comment]
FWIW https://travis-ci.org/github/mfazekas/net-ssh/jobs/677215992 it's 

```
TestForwardOnUnixSockets#test_forward_local_unix_socket_to_remote_port:

Net::SSH::Exception: corrupted hmac detected Net::SSH::Transport::HMAC::SHA2_512_Etm
```

**Comment by ansonhoyt** [comment]
I ran into this doing a Capistrano deploy after this `bundle update`:

```
-    net-scp (2.0.0)
-      net-ssh (>= 2.6.5, < 6.0.0)
-    net-ssh (5.2.0)
+    net-scp (1.2.1)
+      net-ssh (>= 2.6.5)
+    net-ssh (6.0.0)
```

Getting `SSHKit::Runner::ExecuteError: Exception while executing as ahoyt@example.com: corrupted hmac detected`.

Reverting to my previous versions avoids the issue.

**Comment by mfazekas** [comment]
@fwininger i think i'll release a new `net-ssh` 6.0.1 with the `etm` hmac opt-in vs default.

**Comment by mfazekas** [comment]
@ansonhoyt  Can you try with 6.0.1. The algs we suspect are affected are now disabled by default.

**Comment by ansonhoyt** [comment]
Sure, after this `bundle update`, my Capistrano deploy is error free!

```diff
-    net-scp (2.0.0)
-      net-ssh (>= 2.6.5, < 6.0.0)
-    net-ssh (5.2.0)
+    net-scp (1.2.1)
+      net-ssh (>= 2.6.5)
+    net-ssh (6.0.1)
```

Looks like your suspicions are right. Thank you for your maintenance work!

**Comment by fwininger** [comment]
> 
> 
> @fwininger i think i'll release a new `net-ssh` 6.0.1 with the `etm` hmac opt-in vs default.

That fine for me.

It is a good step forward to have found that the problem comes only from ETM algorithms.

For my part, I started a branch with the implementation of the AEAD algorithms (aes-gcm) which are more robust and have no mac. I manage to code the first message block but I have a problem updating the GCM counter on the second block.

**Comment by fzipi** [comment]
Excellent news! I still need to run the tests with different algorithms. But I was thinking about etm also.

**Comment by mfazekas** [comment]
I was able to reproduce the issue using this script:

```ruby
$:.push('./lib')
require 'net/ssh'
require 'byebug'
puts Net::SSH::Version::CURRENT

# Simple TCP server
def start_server(server = nil, &block)
  server ||= TCPServer.open(0)
  Thread.start do
    loop do
      Thread.start(server.accept) do |client|
        yield(client)
      end
    end
  end
  return server
end

PACKET_SIZE_TARGET = 127 # 1024 * 2
PACKET_SIZE_LOCAL = 1024 * 2

def dlog(msg)
  puts "=> #{msg}"
end


# simple TCP server that connection to localhost
def start_frowarding_server(server = nil, remote_host = 'localhost', remote_port = 22)
  server = start_server(server) do |local|
    remote = TCPSocket.new(remote_host, remote_port)
    loop do
      r,w,e = IO.select([local, remote],nil,nil)
      if r.include? local
        data = local.recv PACKET_SIZE_LOCAL rescue data,err = nil, $!
        if data.nil? || data.empty? 
          dlog "Local closed: #{data.inspect} #{err.inspect}"
          break
        end
        dlog "Forwarding: #{data.length} to remote"
        begin
          ret = remote.write data
        rescue => err
          dlog "remote closed: #{err}"
          break
        end
      end
      if r.include? remote
        data = remote.recv PACKET_SIZE_TARGET rescue data,err = nil, $!
        if data.nil? || data.empty?
          dlog "Remote closed: #{data.inspect} #{err.inspect}"
          break
        end
        dlog "Forwarding: #{data.length} to local"
        begin
         ret = local.write data
        rescue => err
          dlog "local closed: #{err}"
          break
        end
      end
    end

    dlog "Closing..."
    local.close
    remote.close
  end
  return server
end

server = start_frowarding_server
port = server.addr[1]
# port = 22

hmac_options = { }
hmac_options = { hmac: ['hmac-sha2-512']}
# hmac_options = { hmac: ['hmac-sha2-512-etm@openssh.com'] }
# hmac_options = { hmac: ['hmac-sha2-256-etm@openssh.com'] }
# hmac_options = hmac_options.merge({verbose: :debug})

ssh = Net::SSH.start('127.0.0.1', ENV["USER"], hmac_options.merge({port: port}))
(1...400).each do |i|
  ret = ssh.exec!("echo \"#{'f'*i}\"")
  puts "=> #{i}" if (i % 10 ==0)
end

ssh.close
puts "OK!"
```

Must be related with the case where we cannot read the full packet, but i don't see the issue in code:

https://github.com/net-ssh/net-ssh/blob/9bed3c7f210ac5de54e6b787cce8498f10ce5c79/lib/net/ssh/transport/packet_stream.rb#L222-L236

**Comment by mfazekas** [comment]
Actually the bug seems to be this:


https://github.com/net-ssh/net-ssh/blob/9bed3c7f210ac5de54e6b787cce8498f10ce5c79/lib/net/ssh/transport/packet_stream.rb#L224-L225

it should be:

```ruby
return nil if available < minimum  + aad_length
data = read_available(minimum + aad_length) 
```

**Comment by fzipi** [comment]
Good catch!

**Comment by fwininger** [comment]
I think this can solve the issue.

**Comment by mfazekas** [comment]
I've released 6.0.2 with etm hmac fixed, but still disabled by default. 
I've also released 6.1.0.rc1 with etm hmac fixed and preferred.

**Comment by stillhart** [comment]
I get the following random error in a specific scenario using 6.1.0.rc1:
```
corrupted hmac detected Net::SSH::Transport::HMAC::SHA1
```

I am upgrading from 5.X.X and I had to opt-in on `append_all_supported_algorithms: true` first. I got the following error before:

```
Server kex preferences: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
Client kex preferences: ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1
```

My output looks as follows:
```
Real hmac: "4\x17\x054\xFB\x81D=\x96\xA6j\xB0\x903\x8Be\x1A?yc"
My hmac: "\x10\xEAi\x87\xE3\x18\x11\xCB\x9Bq\x9C\xD6\x82\xF3\xA8\xF1f2$\xA4"
packet_length: 65564 padding_length: 18
server.hmac.mac_length: 20
server.hmac.etm :false
need: 65552 data:65552

Real hmac: "g\xD1\x9B\x11\x00\x8F\x95~\xF6\xBC'\x01:w\xD0E\x8B\x80U\xF1"
My hmac: "\xD5N\x96&\xC2\x1F\x84B\x81\xBF\xFC\xE3\x94B\xB1\nk\x99\xF2\\"
packet_length: 65564 padding_length: 18
server.hmac.mac_length: 20
server.hmac.etm :false
need: 65552 data:65552

Real hmac: "\xB0\xD2\x02\xD1\xC5>\xB8\xC0\xBD\x0F8>\x83\"\xAE\xC7&f\xF1\xB4"
My hmac: "M\x93\xF9zMn`*\xFC\xFC\xF1\x94\xE2\xA4\xEF\xAD\xA3N>\x92"
packet_length: 65564 padding_length: 18
server.hmac.mac_length: 20
server.hmac.etm :false
need: 65552 data:65552

Real hmac: "\xE0/G\xA1\xAD\x9C\xEB\x92\x92\xC9\xC8'\xB1\xF4\xE7\x84\xA4\xE9@X"
My hmac: "I=a\xDE\xE5p\x14@\xB6\xF2\xA0\xE2b\x93\x0F\x88\xB5\xEE\xB3\xF9"
packet_length: 65564 padding_length: 18
server.hmac.mac_length: 20
server.hmac.etm :false
need: 65552 data:65552
```

I have no idea whether this could be related to the use of insecure algorithms. I would assume some https://github.com/ytti/oxidized/issues/1952 users still have the same issues.

If somebody else still has the issue, please give a 👍. I do not trust the ssh implementation of our devices all that much, it could be server side too.

**Comment by mfazekas** [comment]
@stillhart thanks for the detailed report,  and you don't see this error with `net-ssh` `5.*`?

The `65564` numbers might suggest some overflow error if `shorts` are used somewhere.

Maybe a new issue could be opened for this, as this seems to be different from the etm hmac issue that affected 6.0 and 6.0.1

**Comment by stillhart** [comment]
@mfazekas I saw the same in `net-ssh` `5.*` too. I would not create a new issue unless somebody else has the same problem. The error happens only every ~50th try. I couldn't reproduce same error using standard `ssh`. The issue could be in `net-ssh` but I am not certain at all. I assume the same issue should still show up in https://github.com/ytti/oxidized/issues/1952, if it was one.

**Comment by ljmoleiro** [comment]
> Sure, after this `bundle update`, my Capistrano deploy is error free!
> 
> ```diff
> -    net-scp (2.0.0)
> -      net-ssh (>= 2.6.5, < 6.0.0)
> -    net-ssh (5.2.0)
> +    net-scp (1.2.1)
> +      net-ssh (>= 2.6.5)
> +    net-ssh (6.0.1)
> ```
> 
> Looks like your suspicions are right. Thank you for your maintenance work!

Solve with the update

**Comment by andrewhavens** [comment]
I'm running into this error using 6.1.0:
```
corrupted hmac detected Net::SSH::Transport::HMAC::SHA2_512_Etm (Net::SSH::Exception)
```

I immediately started running into this issue when I started trying to use threads. I am wondering if maybe the main thread is trying to close the session while the other thread is trying to use it.

**Comment by jgrund** [comment]
We are also hitting:

```
corrupted hmac detected Net::SSH::Transport::HMAC::SHA2_512_Etm

/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/transport/packet_stream.rb:285:in `poll_next_packet'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/transport/packet_stream.rb:99:in `next_packet'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:193:in `block in poll_message'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:190:in `loop'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/transport/session.rb:190:in `poll_message'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:546:in `dispatch_incoming_packets'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:249:in `ev_preprocess'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/event_loop.rb:104:in `each'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/event_loop.rb:104:in `ev_preprocess'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/event_loop.rb:28:in `process'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:226:in `process'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:179:in `block in loop'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:179:in `loop'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/session.rb:179:in `loop'
/opt/vagrant/embedded/gems/gems/net-ssh-7.2.1/lib/net/ssh/connection/channel.rb:272:in `wait'
```

with net-ssh-7.2.1.
